atillaLearn/atillaLearn/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import web.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(web.urls)),
]

atillaLearn/web/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^trainings$', views.TrainingListView.as_view(), name='trainings'),
    url(r'^talks$', views.TalkListView.as_view(), name='talks'),
    url(r'^conferences$', views.ConferenceListView.as_view(), name='conferences'),
    url(r'^(?P<pk>[0-9]+)/$', views.ItemDetailView.as_view(), name='detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

atillaLearn/web/models.py
from django.db import models

TYPES_CHOICE = (
		("conference", "Conférence"),
		("training", "Formation"),
		("talk", "Talktilla")
	)

# Create your models here.
class Item(models.Model):


	CONFERENCE = 0
	TRAINING = 1
	TALK = 2
	TYPES_CHOICE = (
		(CONFERENCE, "Conférence"),
		(TRAINING, "Formation"),
		(TALK, "Talktilla")
	)
	type = models.SmallIntegerField("Type", choices=TYPES_CHOICE)
	title = models.CharField("Titre",  max_length=250)
	date = models.DateField("Date de la présentation", null=True, blank=True)
	short = models.TextField("Courte description", blank=True)
	replay_id = models.CharField("Id du replay youtube",  max_length=50, blank=True)
	image = models.FileField(upload_to='images/', blank=True)

	def __str__(self):
		return self.get_type_display() + " " + self.title

atillaLearn/web/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Item
# Create your views here.

def index(request):
    return render_to_response('index.html')

class TrainingListView(ListView):

    model = Item
    queryset = Item.objects.filter(type=Item.TRAINING)
    template_name = 'trainings.html'

class TalkListView(ListView):

    model = Item
    queryset = Item.objects.filter(type=Item.TALK)
    template_name = 'talks.html'

class ConferenceListView(ListView):

    model = Item
    queryset = Item.objects.filter(type=Item.CONFERENCE)
    template_name = 'conferences.html'

class ItemDetailView(DetailView):

    model = Item
    template_name = 'item_detail.html'
    context_object_name = 'item'

atillaLearn/web/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns/website#">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0">
    <meta name="google-site-verification" content="30rEodAdJUH7y9YsTZI1RyWm3M3Xt2qIuRzfX-OgydU" />

    <link rel="icon" href="http://cdn.atilla.org/ico/favicon.ico">

    {# OpenGraph metadata #}
    <meta property="og:title" content="{{ title }}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="{{ meta.url }}" />
    <meta property="og:image" content="{{ meta.image }}" />
    <meta property="og:site_name" content="Atilla">

    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'vendor/Materialize/bin/materialize.css' %}" media="screen,projection"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" charset="utf-8">

    <title>{% block title %}{{ title }}{% endblock %}</title>
    <meta name="description" content="{% block description %}Learn est la plateforme d'appretissage de Atilla. Retrouvez nos talks, formations et conférences.{% endblock %}">

  </head>

  <body>
    {# Header #}
    <header>
        <div class="side-nav fixed" id="mobile-demo">
          <a href="{% url 'index' %}" class="brand-logo flow-text blue-grey darken-3">
            <span class="yellow-text text-darken-2">>~/</span>Learn
          </a>

          <ul style="width:240px;">
            <li><a class="flow-text" href="{% url 'trainings' %}">Formations <span class="badge">{{ num.trainings }}</span></a></li>
            <li><a class="flow-text" href="{% url 'talks' %}">Talks <span class="badge">{{ num.talks }}</span></a></li>
            <li><a class="flow-text" href="{% url 'conferences' %}">Conférences <span class="badge">{{ num.conferences }}</span></a></li>
          </ul>

          <div class="partners center">
            <p>
              En partenariat avec
            </p>
            <img src="{% static 'img/eisti.png' %}" alt="" />
          </div>
        </div>
    </header>

    {# Main content #}
    <main>
        <nav>
          <div class="nav-wrapper grey lighten-3">
            <div class="container">
              <a href="#" data-activates="mobile-demo" class="button-collapse grey-text"><i class="material-icons">menu</i></a>
              <a href="#!" class="brand-logo">{% block subtitle %}{% endblock %}</a>

              <div class="right hide-on-small-only" style="padding-top:7px;">
                <a href="https://twitter.com/cy106" target="_blank"><img height="50" width="50" src="{% static 'img/twitter.png' %}"></a>
                <a href="https://www.facebook.com/atilla.org/" target="_blank"><img height="50" width="50" src="{% static 'img/fb.png' %}"></a>
                <a href="https://www.youtube.com/channel/UCvhqFFyH0V-6FBhzvuG58Jg" target="_blank"><img height="50" width="50" src="{% static 'img/youtube.png' %}"></a>
              </div>
            </div>
          </div>
        </nav>
    {% block content %}
    {% endblock %}
    </main>

    {# Footer #}
    <footer class="page-footer blue-grey darken-5">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Learn Atilla</h5>
            <p class="grey-text text-lighten-4">Site proposé par l'association <a href="http://atilla.org" class="atilla">Atilla</a>.</p>
            {% comment %}
            <p class="grey-text text-lighten-4">Généré le {{ gen_time.strftime("%d/%m/%Y") }} à {{ gen_time.strftime("%H:%M") }},
              révision <a href="https://github.com/Atilla-Learn/portal/commit/{{ git_sha1 }}">{{ git_sha1 }}</a>.</p>
            {% endcomment %}
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Liens</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="{% url 'trainings' %}">Formations</a></li>
              <li><a class="grey-text text-lighten-3" href="{% url 'talks' %}">Talks</a></li>
              <li><a class="grey-text text-lighten-3" href="{% url 'conferences' %}">Conférences</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2015 Atilla
        <!-- <a class="grey-text text-lighten-4 right" href="#!">More Links</a> -->
        </div>
      </div>
    </footer>



    {# Script #}
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="{% static 'vendor/Materialize/bin/materialize.js' %}"></script>

    {% block script %}{% endblock %}

    <script type="text/javascript">
         $(".button-collapse").sideNav();
    </script>


  </body>
</html>

atillaLearn/web/templates/conferences.html
{% extends 'item_list.html' %}

{% load staticfiles %}

{% block title %}Les conférences{% endblock %}
{% block description %}Liste des conférences proposée par Atilla{% endblock %}
{% block subtitle %}Conférences{% endblock %}

{% block list_title %}Conférences{% endblock %}
{% block list_description %}Vous trouverez ici toutes les conférences. Et ça c'est cool.{% endblock %}

atillaLearn/web/templates/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block subtitle %}Présentation{% endblock %}

{% block content %}
  <div class="row blue-grey darken-3">
    <div class="col offset-m2 m8 s12">
      <img src="{% static 'img/prompt.png' %}" class="responsive-img">
    </div>
    <div class="col s12 blue-grey darken-2 center">
      <h4>
        <span class="flow-text white-text">Bienvenue sur la plateforme d'apprentissage d'</span><b><span class="flow-text yellow-text text-darken-2">ATILLA</span></b>
      </h4>
    </div>
  </div>
  <div class="row container">
    <div class="col s12">
      <h6 class="flow-text center"> Ce qu'on vous propose ? </h6>
    </div>
    <div class="container">
      <div class="col s12">
        <h5 class="flow-text center grey-text"> Une plateforme regroupant des formations, des talks et des conférences, le tout alimenté par une recette secrète à base de barbus et de cookies.</h5>
      </div>
    </div>
    <div class="col s6 offset-s3 center">
      <a class="btn-floating  btn-large waves-effect waves-light yellow darken-2" id="topbutton"><i class="mdi-navigation-expand-more"></i></a>
    </div>
  </div>
  <div class="row container" style="overflow-x:hidden">
    <div class="col s12">
      <h3 class="yellow-text text-darken-3">Formations</h3>
    </div>
    <div class="col s6">
      <br>
      <p class="flow-text" align="justify">
        Nous vous proposons de nombreuses formations sur des sujets variés. Vous pouvez ainsi découvrir un nouveau langage de programmation, une nouvelle bibliothèque logicielle ou comment utiliser un logiciel.
      </p>
      <p align="justify">
        Vous pouvez revoir les formations comme si vous y étiez, les cookies en moins.
      </p>
      <br>
      <a class="waves-effect waves-light btn-large yellow darken-3" href="trainings.html">
        <i class="material-icons left">code</i>
        Voir les formations
      </a>
    </div>
    <div class="col s5 offset-s1">
      <img src="{% static 'img/logocircle.png' %}" width="100%">
    </div>
  </div>

  <div class="blue-grey darken-2">
    <div class="row container" style="padding-top:20px;">
      <div class="col s12">
        <h3 class="white-text">Talks</h3>
      </div>
      <div class="col s5 center">
        <img src = "{% static 'img/prompt_talks.png' %}" class="responsive-img" width="90%">
      </div>
      <div class="col s6 offset-s1">
        <p class="white-text flow-text" align="justify" style="padding: 1px 0;">
          Un groupe composé de membres d'Atilla et d'invités discute d'un sujet en rapport avec l'informatique au sens large : logiciel libre, défense de l'internet ou "boucle-if le meurtre comme solution" font partie de nos sujets de prédilections.
        </p>
        <a class="waves-effect waves-light btn-large yellow darken-3" href="talks.html">
          <i class="mdi-social-group right"></i>Voir les talktillas
        </a>
        <p style="padding: 1px 0;"></p>
      </div>
    </div>
  </div>
  <p style="padding: 1px 0;"></p>
  <div class="row container">
    <div class="col s12">
      <h3 class="yellow-text text-darken-3">Conférences</h3>
    </div>
    <div class="col s6">
      <p class="flow-text valign-wrapper" align="justify">
        Tout au long de l'année, Atilla vous propose des conférences. Si vous n'avez pas pu y aller et ne vous inquiétez pas, toutes les conférences sont disponibles en vidéo !
      </p>
      <p align="justify" style="padding: 1px 0;">
        N'hésitez pas à vous renseigner sur les conférences à venir.
      </p>
      <a class="waves-effect waves-light btn-large yellow darken-3" href="conferences.html">
        <i class="mdi-social-person left"></i>Voir les conférences
      </a>
    </div>
    <div class="col s5 offset-s1">
      <p style="padding: 1px 0;"></p>
      <img src="{% static 'img/prompt_confs.png' %}" class="valign responsive-img" width="90%">
    </div>
  </div>
  <p style="padding: 1px 0;"></p>
{% endblock %}

{% block script %}
<script>
$(document).ready(function(){
  $('#topbutton').click(function(){
    $('html, body').animate({
           scrollTop: 790
       }, 800);
  });
  $('ul.tabs').tabs();
});
</script>
{% endblock %}

atillaLearn/web/templates/item_detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block subtitle %}
{% if item.type == item.CONFERENCE %}
Conférences >
{% elif item.type == item.TRAINING %}
Formations >
{% elif item.type == item.TALK  %}
Talktillas >
{% endif %}
{{item.title}}
{% endblock %}

{% block content %}

<div class="container">
  <h3 class="yellow-text text-darken-2">{{item.title}}</h3>
  <p class="flow-text">{{item.short}}</p>
  <div class="card-panel">

    {% if item.replay_id %}
      <div class="video-container center">
        <iframe width="1280" height="720" src="https://www.youtube.com/embed/{{item.replay_id}}" frameborder="0" allowfullscreen></iframe>
      </div>
    {% elif item.image %}
      <div class="center">
        <img src="/media/{{item.image}}" class="responsive-img"/>
      </div>
    {% else %}
      <div class="center">
        Il n'y a pas de replay.
      </div>
    {% endif %}

  </div>
  <div class="row">
    <div class="col l7 s12">
      <div class="card-panel teal">
        <span class="white-text">
          <h4>Description</h4>
          {{item.short}}
        </span>
      </div>

    </div>
    <div class="col l5 s12">
      <div class="card grey darken-3">
        <div class="card-content white-text">
          <span class="flow-text"><i class="fa fa-calendar-o"></i>  {{item.date|date:"SHORT_DATE_FORMAT"}}</span>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock %}

{% block script %}
<script>
$(document).ready(function(){
  $('#topbutton').click(function(){
    $('html, body').animate({
           scrollTop: 790
       }, 800);
  });
  $('ul.tabs').tabs();
});
</script>
{% endblock %}

atillaLearn/web/templates/item_list.html
{% extends 'base.html' %}

{% load staticfiles %}


{% block content %}

  <div class="container">

    <h3 class="yellow-text text-darken-2">{% block list_title %} {% endblock %}</h3>
    <p class="flow-text">
      {% block list_description %} {% endblock %}
    </p>

    {% for item in object_list %}
      <div class="row">
        <a class="col m6 s12" href="{% url 'detail' item.pk %}">
        <div class="card-panel no-padding row z-depth-1 hoverable black-text">
        <div class="col s4 no-padding">
          {% if item.image %}
            <img src="/media/{{item.image}}" class="responsive-img"/>
          {% else %}
            <img src="{% static 'img/prompt_talks.png' %}" class="responsive-img"/>
          {% endif %}
        </div>
        <div class="col s8">
          <h4 class="date"><i class="fa fa-calendar-o"></i> {{item.date|date:"SHORT_DATE_FORMAT"}}</h4>
          <h2 class="name">{{item.title}}</h2>
          <p>{{item.short}}</p>
        </div>
        </div>
        </a>
      </div>
    {% endfor %}

  </div>

{% endblock %}

{% block script %}
<script>
$(document).ready(function(){
  $('#topbutton').click(function(){
    $('html, body').animate({
           scrollTop: 790
       }, 800);
  });
  $('ul.tabs').tabs();
});
</script>
{% endblock %}

atillaLearn/web/templates/talks.html
{% extends 'item_list.html' %}

{% load staticfiles %}

{% block title %}Les talktillas{% endblock %}
{% block description %}Liste des talks proposée par Atilla{% endblock %}
{% block subtitle %}Talktillas{% endblock %}

{% block list_title %}Talks{% endblock %}
{% block list_description %}Vous trouverez ici tous les talks. Et ça c'est cool.{% endblock %}

atillaLearn/web/templates/trainings.html
{% extends 'item_list.html' %}

{% load staticfiles %}

{% block title %}Les formations{% endblock %}
{% block description %}Liste des formations proposée par Atilla{% endblock %}
{% block subtitle %}Formations{% endblock %}

{% block list_title %}Formations{% endblock %}
{% block list_description %}Vous trouverez ici toutes les formations. Et ça c'est cool.{% endblock %}